# Chapter 10 — Row Reduction and LU Decomposition

## Learning Objectives

This notebook covers systems of equations, row reduction intuition, Gaussian elimination, LU decomposition, and solving linear systems.

## Theoretical Explanation

Systems of equations can be written as `Ax=b`. Row reduction transforms the coefficient matrix into an easier form while preserving the solution. LU decomposition factors a matrix into a lower-triangular matrix and an upper-triangular matrix. This supports efficient solving, determinant computation, and inverse-related operations.

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import norm, matrix_rank

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

## 1. Solving a Linear System

In [2]:
A = np.array([[2.,1.], [1.,3.]])
b = np.array([8., 13.])
x = np.linalg.solve(A,b)
print('solution x:', x)
print('A @ x:', A @ x)
print('target b:', b)

solution x: [2.2 3.6]
A @ x: [ 8. 13.]
target b: [ 8. 13.]


### Output Interpretation

The solution vector satisfies the original system. `np.linalg.solve` is preferred over explicitly computing the inverse for numerical stability.

## 2. LU Decomposition with SciPy

In [3]:
import scipy.linalg as la
A = np.array([[2.,1.,1.], [4.,-6.,0.], [-2.,7.,2.]])
P, L, U = la.lu(A)
print('P:\n', P)
print('L:\n', np.round(L,3))
print('U:\n', np.round(U,3))
print('Reconstruction error:', norm(A - P @ L @ U))

P:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]
U:
 [[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]
Reconstruction error: 0.0


### Output Interpretation

The matrix is decomposed into permutation, lower-triangular, and upper-triangular factors. These factors encode row swaps and elimination steps.

## Extended Study Notes

The central learning objective is not only to run code, but to connect the numerical result back to the linear algebra idea. In applied data science, vectors and matrices are not abstract objects only; they are the representation layer for observations, features, images, time series, model parameters, transformations, and decompositions.

A professional workflow should always include sanity checks. For example, reconstructed matrices should be compared with the original matrix, orthogonal matrices should be checked with `Q.T @ Q`, inverse computations should be checked against the identity matrix, and least-squares predictions should be inspected through residuals. These checks make the notebook academically stronger and reduce the risk of blindly trusting a black-box function.

## Chapter Summary

This notebook reproduces the core concept of the chapter using original/adapted Python examples. The code is intentionally compact but runnable, and the surrounding explanation focuses on conceptual understanding, interpretation, and practical relevance for data science.

## Key Takeaways

- Linear algebra concepts become clearer when formulas, geometry, and code are studied together.
- NumPy provides efficient implementations, but understanding the underlying math helps prevent misuse.
- Shape, rank, orientation, and numerical stability are recurring concerns in applied linear algebra.
- Every output should be interpreted as evidence of a mathematical property, not merely as a printed result.