# Chapter 6 — Matrices, Part 2

## Learning Objectives

This notebook covers matrix norms, trace, column space, row space, null space, rank, determinant, and the characteristic polynomial.

## Theoretical Explanation

Matrix rank measures how many independent directions of information exist in a matrix. Rank connects linear independence, invertibility, column space, and null space. The determinant is defined only for square matrices and becomes zero when the matrix is singular.

The Frobenius norm summarizes the magnitude of all matrix entries. The trace sums diagonal entries and connects to eigenvalues later. These quantities appear in regularization, optimization, and numerical diagnostics.

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import norm, matrix_rank

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

## 1. Frobenius Norm and Trace

In [2]:
A = np.random.randn(4,5)
frob_direct = np.sqrt(np.sum(A**2))
frob_np = norm(A, 'fro')
trace_method = np.sqrt(np.trace(A.T @ A))
print('Frobenius direct:', frob_direct)
print('Frobenius NumPy:', frob_np)
print('Trace method:', trace_method)

Frobenius direct: 4.25420977062536
Frobenius NumPy: 4.254209770625359
Trace method: 4.254209770625359


### Output Interpretation

All three methods agree. The trace method works because the diagonal of `A.T @ A` contains column dot products with themselves.

## 2. Rank and Linear Dependence

In [3]:
B = np.array([[1,2,3], [2,4,6], [1,0,1]])
print('Matrix B:\n', B)
print('Rank of B:', matrix_rank(B))
print('Max possible rank:', min(B.shape))
print('Determinant:', np.linalg.det(B))

Matrix B:
 [[1 2 3]
 [2 4 6]
 [1 0 1]]
Rank of B: 2
Max possible rank: 3
Determinant: 0.0


### Output Interpretation

The matrix is rank-deficient because one row is a multiple of another. Its determinant is zero or numerically close to zero, indicating singularity.

## 3. Column Space Test by Rank Augmentation

In [4]:
A = np.array([[1,0], [0,1], [1,1]])
v_in = np.array([[2], [3], [5]])
v_out = np.array([[2], [3], [6]])
for name, v in [('v_in', v_in), ('v_out', v_out)]:
    augmented = np.hstack([A, v])
    print(name, 'rank A =', matrix_rank(A), 'rank augmented =', matrix_rank(augmented), 'in column space?', matrix_rank(A)==matrix_rank(augmented))

v_in rank A = 2 rank augmented = 2 in column space? True
v_out rank A = 2 rank augmented = 3 in column space? False


### Output Interpretation

If augmenting the matrix with the vector does not increase rank, the vector is already in the column space. If rank increases, the vector adds a new direction.

## Extended Study Notes

The central learning objective is not only to run code, but to connect the numerical result back to the linear algebra idea. In applied data science, vectors and matrices are not abstract objects only; they are the representation layer for observations, features, images, time series, model parameters, transformations, and decompositions.

A professional workflow should always include sanity checks. For example, reconstructed matrices should be compared with the original matrix, orthogonal matrices should be checked with `Q.T @ Q`, inverse computations should be checked against the identity matrix, and least-squares predictions should be inspected through residuals. These checks make the notebook academically stronger and reduce the risk of blindly trusting a black-box function.

## Chapter Summary

This notebook reproduces the core concept of the chapter using original/adapted Python examples. The code is intentionally compact but runnable, and the surrounding explanation focuses on conceptual understanding, interpretation, and practical relevance for data science.

## Key Takeaways

- Linear algebra concepts become clearer when formulas, geometry, and code are studied together.
- NumPy provides efficient implementations, but understanding the underlying math helps prevent misuse.
- Shape, rank, orientation, and numerical stability are recurring concerns in applied linear algebra.
- Every output should be interpreted as evidence of a mathematical property, not merely as a printed result.