# Chapter 8 — Matrix Inverse

## Learning Objectives

This notebook covers full inverse, one-sided inverse, pseudoinverse, invertibility conditions, numerical stability, and geometric interpretation.

## Theoretical Explanation

The inverse of a matrix reverses a linear transformation and solves equations of the form `Ax=b`. A full inverse exists only for square full-rank matrices. Tall or wide matrices may have one-sided inverses when they have maximum possible rank. Every matrix has a Moore-Penrose pseudoinverse.

In applied work, explicit inversion should be used carefully because ill-conditioned matrices amplify numerical error. Solvers and decompositions are often preferred.

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import norm, matrix_rank

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

## 1. Full Inverse

In [2]:
A = np.array([[2,1], [1,3]])
Ainv = np.linalg.inv(A)
print('A inverse:\n', Ainv)
print('A @ Ainv:\n', np.round(A @ Ainv, 6))

A inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A @ Ainv:
 [[ 1.  0.]
 [-0.  1.]]


### Output Interpretation

The product is the identity matrix, confirming that `Ainv` reverses the transformation represented by `A`.

## 2. Left Inverse for Tall Matrix

In [3]:
T = np.random.randn(6,3)
L = np.linalg.inv(T.T @ T) @ T.T
print('T shape:', T.shape)
print('L shape:', L.shape)
print('L @ T:\n', np.round(L @ T, 6))

T shape: (6, 3)
L shape: (3, 6)
L @ T:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


### Output Interpretation

A full-column-rank tall matrix can have a left inverse. Multiplying from the left returns the identity matrix of size equal to the number of columns.

## 3. Pseudoinverse for Singular Matrix

In [4]:
S = np.array([[1,2], [2,4]])
print('rank:', matrix_rank(S))
Sinv = np.linalg.pinv(S)
print('pseudoinverse:\n', np.round(Sinv, 3))
print('S @ pinv(S):\n', np.round(S @ Sinv, 3))

rank: 1
pseudoinverse:
 [[0.04 0.08]
 [0.08 0.16]]
S @ pinv(S):
 [[0.2 0.4]
 [0.4 0.8]]


### Output Interpretation

The matrix is singular and has no full inverse, but the pseudoinverse still exists. The product is not the exact identity, but it provides the best generalized inverse behavior.

## Extended Study Notes

The central learning objective is not only to run code, but to connect the numerical result back to the linear algebra idea. In applied data science, vectors and matrices are not abstract objects only; they are the representation layer for observations, features, images, time series, model parameters, transformations, and decompositions.

A professional workflow should always include sanity checks. For example, reconstructed matrices should be compared with the original matrix, orthogonal matrices should be checked with `Q.T @ Q`, inverse computations should be checked against the identity matrix, and least-squares predictions should be inspected through residuals. These checks make the notebook academically stronger and reduce the risk of blindly trusting a black-box function.

## Chapter Summary

This notebook reproduces the core concept of the chapter using original/adapted Python examples. The code is intentionally compact but runnable, and the surrounding explanation focuses on conceptual understanding, interpretation, and practical relevance for data science.

## Key Takeaways

- Linear algebra concepts become clearer when formulas, geometry, and code are studied together.
- NumPy provides efficient implementations, but understanding the underlying math helps prevent misuse.
- Shape, rank, orientation, and numerical stability are recurring concerns in applied linear algebra.
- Every output should be interpreted as evidence of a mathematical property, not merely as a printed result.